### PR TITLE
1.20.1 (Unfortunate Coincidences edition)

### PR DESCRIPTION
**Pull request by neirenoir**
I started working on this two days ago and I just noticed someone also started working on this two days ago. Whoops.

#39 probably did a better job at updating the mod to a newer version. This is literally my first time doing something related to Minecraft modding and I am kind of overwhelmed by the lack of documentation. Expect many of my changes to be non-idiomatic.

However, this PR also includes:
1. Support for the Paraglider mod.
2. A custom StaminaPlugin for Paraglider that will override their stamina system with Feathers (sort of: it just lets AoS handle almost all of the stamina logic). It is toggable through config options.
3. A fix for the armor weight calculation that allows players at 100% weight still break blocks while simultaneously behaving more consistently with flying actions.
4. #39 and this PR share dropped support for WallJump. Sadly, it is not available for 1.20.1. However, my PR keeps it commented out just in case it gets readded at a later date.

### CODE REVIEW

**Comment by CCr4ft3r** [comment]
True ... that documentation aspect is kind of a bummer. But studying other repostiories helped me a lot in the beginning. It's definitely getting better by time.
I appreciate your contribution as well. However I will not be able to maintain this project in foreseeable future.
I offered @Darkona to take over this project. If you are also interested, the two of you could get in touch.
I believe the mod would be in good hands with both of you.

**Comment by Darkona** [comment]
Wel maybe I can take a look at this PR and reinclude the paraglider support into mine, let's just merge what was done so not duplicate work. (I just couldn't figure it out and wanted a version for a private server where i dont use paraglider). I'm no entirely sure I could take over the mod forever, but I can help maintain it for the time being. Its good it is open source so anybody else can pick it up later again. For now its good that it gets updated to 1.20.1 which is a popular version and later on for newer versions, we'll see.

**Comment by Darkona** [comment]
https://discord.gg/HQq3cMYy you can reach me here if you want so we can have a quick chat, both of you. cheers

**Comment by Darkona** [comment]
Hi @neirenoir , I have taken over the project with the approval of CCr4ft3r. Would you be so kind to reopen this PR pointing to the 1.20.1 branch? I will merge your changes to the paraglider support that i removed to have a more complete version. I already took some of your changes, so maybe you might want to see some conflicts first?

**Comment by Darkona** [comment]
Please be so kind to reopen pointing to the 1.20.1 branch <3

**Pull request closed without merging**
